% This function loads training options for the trainNetwork.
% input,
% val: validation dataset. Here, in our project, the format should be
% augmentPlaneImageDatastore.
% output,
% Options: TrainingOptions.
% Change the dirCheckPoint if necessary.
%

function Options = loadOptions(val)
Options =  trainingOptions('adam', ...
    'MaxEpochs',100, ...
    'MiniBatchSize',52, ...
    'ValidationData',val,...
    'ValidationPatience',5,...
    'ValidationFrequency',104,...
    'InitialLearnRate', 0.1,...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.2, ...
    'LearnRateDropPeriod',5, ...
    'ExecutionEnvironment','parallel',...
    'CheckpointPath','D:\Projects\checkpoint',...
    'Plots','training-progress',...
    'Verbose',0);
end
